export const GET_MOVIE_START = "GET_MOVIE_START";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILED = "GET_MOVIE_FAILED";

export const GET_MOVIE_INFO_START = "GET_MOVIE_INFO_START";
export const GET_MOVIE_INFO_SUCCESS = "GET_MOVIE_INFO_SUCCESS";
export const GET_MOVIE_INFO_FAILED = "GET_MOVIE_INFO_FAILED";

export const GET_FIRST_MOVIE_START = "GET_FIRST_MOVIE_START";
export const GET_FIRST_MOVIE_SUCCESS = "GET_FIRST_MOVIE_SUCCESS";
export const GET_FIRST_MOVIE_FAILED = "GET_FIRST_MOVIE_FAILED";

